# This is a basic workflow to help you get started with Actions

name: TestPROGPOE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # list contents or directory
      - name: List contents
        run: ls
      #compiles classes to test
      - name: compile classes
        working-directory: ./src
        run: javac -cp "../testresoureces/junit-platform-console-standalone-1.6.0.jar" ./login/Login.java ./login/LoginDetail.java "../test/login/LoginTest.java"  ../test/login/LoginDetailTest.java" ./login/Task.java ./login/TO_DO_LIST.java "../test/login/TaskTest.java"  ../test/login/TO_DO_LISTTest.java" 
      
      # lists contents of src to verify that classes compliled
      - name: List contents of src directory after compile
        working-directory: ./src/login
        run: ls


      #copy compiled classes to test directory
      - name: copy compiled classes to testresources directory
        working-directory: ./src/login
        run: cp -t "../../test/Login" Task.class Login.class LoginDetail.class TO_DO_TEST.class

      #copy compiled tests
      - name: copy compiled Test classes to testresources directory
        working-directory: ./test/login
        run: cp -t "../../testresources/"  Login.class LoginDetail.class Task.class TO_DO_LIST.class

      # list contents or directory
      - name: List contents test package
        working-directory: ./test/login
        run: ls

      #run Message class tests and output report
      - name: run TO_DO_LIST Class tests and create report
        working-directory: ./test
        run: |
         ls
         java -jar  "../testresoureces/junit-platform-console-standalone-1.6.0.jar" -cp "." --selsect-class login.TO_DO_LISTTest

          #run Message class tests and output report
      - name: run LoginDetail Class tests and create report
        working-directory: ./test
        run: |
         ls
         java -jar  "../testresoureces/junit-platform-console-standalone-1.6.0.jar" -cp "." --selsect-class login.LoginDetailTest
          

   
